### ISSUE TITLE
Support Angular-specific files

### ISSUE THREAD

**Issue by lppedd** [jonathanlermitage/intellij-extra-icons-plugin#1]
Is there a way to establish the "type" of file by scanning the content? This could be helpful for frameworks.
I just asked to the IDEA team, lets see how they manage to discover the file "type", but I think it's only by file name, just as you are doing now.

So for Angular Components, it would be `*.component.ts`.

**Comment by lppedd** [comment]
@jonathanlermitage Yeah, i'll make a PR. I'll take the icons from VSCode if possible.
Would be interesting to understand how to recognize an Angular project. Maybe via the angular.json file?

**Comment by jonathanlermitage** [comment]
I don't know, but you can try to load an Angular project, and print `psiElement` to console in [ExtraIconProvider.java:getIcon](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/src/lermitage/intellij/extra/icons/ExtraIconProvider.java). A `psiElement` property may show "angularjs".

**Comment by lppedd** [comment]
@jonathanlermitage Should look at https://github.com/JetBrains/intellij-plugins/blob/56e197a83ad776dbe736bcf006d0ddb749d413bf/AngularJS/src/org/angular2/lang/Angular2LangUtil.java

Method `isAngular2ContextDir` establishes if it is an Angular project.

**Comment by lppedd** [comment]
@jonathanlermitage I noticed the yellow icon is almost invisible using the light theme. I will provide a custom dark icon for that one
