### ISSUE TITLE
Add buttons to allow reordering of entries in the User Icons list

### ISSUE THREAD

**Issue by lcdennison** [jonathanlermitage/intellij-extra-icons-plugin#100]
This is either a feature request, or a help thread because I don't know what I'm doing. Put simply, I'd like to be able to re-order the icons on the User Icons list (`Settings -> Appearance & Behavior -> Extra Icons -> User Icons tab`). I don't see any way of doing this in the UI currently. It seems they are ordered in whatever way I add them. (So I can manually re-order them by re-adding them.)

---
This is what I see on the User Icons toolbar UI:

![image](https://user-images.githubusercontent.com/9526919/175768740-fbb5be09-a48b-44ad-9a18-0f827d6a284c.png)

I'd expect up/down buttons to move items up or down the list one at a time. These up/down buttons are on other ordered lists in the IDE. Here's a small snip from the Quick Lists UI (red arrow my emphasis obviously).

![image](https://user-images.githubusercontent.com/9526919/175768710-2ba0c978-3896-4364-8c3a-023251756e2a.png)

If this functionality is already available somewhere, could you please point me in that direction?

Plugin: 2022.1.5
IDE: PhpStorm 2022.1.2

**Comment by jonathanlermitage** [comment]
Good idea! I will try to implement this for the 2022.1.6 release.

**Comment by jonathanlermitage** [comment]
@lcdennison can you please try this release?  
[Extra Icons-2022.1.6.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8985680/Extra.Icons-2022.1.6.zip)

I implemented the Move Up and Move Down buttons.

**Comment by jonathanlermitage** [comment]
Implemented.  
@lcdennison can you please try this build? 
[Extra Icons-2022.1.6.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8987572/Extra.Icons-2022.1.6.zip)
Thx!
