### ISSUE TITLE
启动idea2022.2，弹窗提示警告

### ISSUE THREAD

**Issue by zem558** [jonathanlermitage/intellij-extra-icons-plugin#109]
Failed to query IDE filename index. This feature won't work: Helm icons. If this is the first time you see this message, and if you really need these features, please restart your IDE. If it doesn't help, try to clear the file system cache and Local History (go to File, Invalidate Caches...).  To disable this notification, please go to File, Settings..., Extra Icons, and check Ignore plugin's warnings.

**Comment by jonathanlermitage** [comment]
This is a JetBrains issue. I just catched the error in order to avoid a plugin's crash.  
You can go to Extra Icons options to disable this notification.
