### ISSUE TITLE
Gradle vs Devkit

### ISSUE THREAD

**Issue by MatthiasKunnen** [jonathanlermitage/intellij-extra-icons-plugin#11]
I was looking at the [getting started page for creating IntelliJ plugins](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html) and it mentions two workflows, one using DevKit, and one using Gradle. Since this project does not have any Gradle files, I assume it using the old DevKit workflow.

Would it be beneficial to upgrade to using Gradle?

**Comment by jonathanlermitage** [comment]
You're right: I'm using the DevKit workflow.

A Gradle build would offer benefits like:
* easy integration of online CI/build with Travis, AppVeyor...
* contributors would only have to install Gradle. With DevKit, you have to accomplish some annoying configuration steps

So, I agree: upgrading to Gradle build would be very interesting.
