### ISSUE TITLE
Would the plugin support the New UI of IntelliJ?

### ISSUE THREAD

**Issue by chienstone** [jonathanlermitage/intellij-extra-icons-plugin#115]

**Comment by jonathanlermitage** [comment]
Last time I tried the new UI, Extra Icons worked well.  
Do you see any error or stacktrace?

**Comment by jonathanlermitage** [comment]
@chienstone 
I tried today with IJ 2022.3.1 and everything seems to work😀
![Screenshot_newui_20221222](https://user-images.githubusercontent.com/857535/209230685-fe3fd991-f6ec-4371-999f-4cc548e4f1cf.png)

**Comment by chienstone** [comment]
Thank you for the response!
I think I forgot to reopen the IDE. Now the plugin works very well.
