### ISSUE TITLE
intellij sync settings include plugin settings?

### ISSUE THREAD

**Issue by Jarrodsz** [jonathanlermitage/intellij-extra-icons-plugin#116]
Just a quick question. 
Im using the EAP versions of Ultimate and there seems to be no option to easily export plugin settings.
Would it be possible to include the "intelij sync idea" feature for this plugin?

For now my thought was to copy the icon config mappings from file system but could not locate the location where they are stored.

In the lastest intellij idea its not possible to add icons clicking + does nothing.
Not a big deal but would love to have the icons in intellij eap also while working on that untill stable is released

**Comment by jonathanlermitage** [comment]
Hi!  
All plugins settings can be exported.  
![export-settings](https://user-images.githubusercontent.com/857535/217891554-7648e462-b27f-40ec-95de-921ee78b1a04.png)

If you cannot export some settings from EAP versions, this is probably a bug in IJ. I think you can open an issue on JetBrains [YouTrack](https://youtrack.jetbrains.com/issues).

Please note that it works for IDE level settings. If you defined some settings at the project level, these settings are stored in the corresponding project's directory, in `.idea/misc.xml`.

**Comment by jonathanlermitage** [comment]
Yeah, the plugin's IDE settings are stored in `lermitage-extra-icons.xm`.

Hum, bad news 😅. Could you please share the url of the opened issue? I would like to upvote. Thx!

**Comment by jonathanlermitage** [comment]
BTW, if the export/sync features are broken since a while, I will develop an export tool for ExtraIcons. It should be easy.

**Comment by jonathanlermitage** [comment]
I just tried to import and export plugin's settings with IntelliJ 2023.1, and everything worked fine. Maybe this is fixed?
