### ISSUE TITLE
An error submitter that pre-fills a new issue in GitHub would be useful for error reporting

### ISSUE THREAD

**Issue by PawelLipski** [jonathanlermitage/intellij-extra-icons-plugin#118]
See https://github.com/VirtusLab/git-machete-intellij-plugin/blob/v3.6.0/frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/errorreport/GitMacheteErrorReportSubmitter.java for a well-tested solution

**Comment by jonathanlermitage** [comment]
Implemented. Thanks for the suggestion and the link :+1:
