### ISSUE TITLE
"Restart" could set a bit wider

### ISSUE THREAD

**Issue by gerryhjs** [jonathanlermitage/intellij-extra-icons-plugin#120]
![image](https://user-images.githubusercontent.com/45413498/224452398-ea639d05-f2b4-4d23-bb61-653543238f21.png)

The last Chinese character is displayed as omitted, set a bit wider should solved.

**Comment by gerryhjs** [comment]
Add: Computer resolution is 1920x1080 Zoom 1.25 （default setting of Windows）
It looks fine on  1920x1080 Zoom 1.0

**Comment by jonathanlermitage** [comment]
It should be fixed now. I packaged this version: 
[Extra Icons-2023.1.2.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/10949409/Extra.Icons-2023.1.2.zip)

**Comment by jonathanlermitage** [comment]
Packaged a new version. The "Quick action" field were no translated 😅
[Extra Icons-2023.1.2.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/10949539/Extra.Icons-2023.1.2.zip)  
Everything should be good now.

**Comment by gerryhjs** [comment]
Test it works good now :)
