### ISSUE TITLE
icon pack: old file icons

### ISSUE THREAD

**Issue by jonathanlermitage** [jonathanlermitage/intellij-extra-icons-plugin#124]
Create an Icon Pack that replaces new UI file icons by old icons. For people who like the new UI but no the new file icons ;)  

WIP

**Comment by jonathanlermitage** [comment]
https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/themes/THEMES.md

**Comment by jonathanlermitage** [comment]
[Extra Icons-2023.1.2.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11095817/Extra.Icons-2023.1.2.zip)

**Comment by gerryhjs** [comment]
![image](https://user-images.githubusercontent.com/45413498/231125370-259b51a8-f861-45fd-8829-4d585ca96016.png)
i18n I think it should be "export" here, could use→ "导出"

**Comment by jonathanlermitage** [comment]
I will fix this. Thanks!
