### ISSUE TITLE
New icon Avro .avsc file

### ISSUE THREAD

**Issue by wokier** [jonathanlermitage/intellij-extra-icons-plugin#14]
Please add an icon for .ascv avro schema file.
It is json based
At least reuse json icon is fine.
Thanks

**Comment by jonathanlermitage** [comment]
Could you send me the PNG or SVG file?  
Or should I simply use https://avro.apache.org/docs/1.8.1/images/avro-logo.png logo?
Thx.

**Comment by jonathanlermitage** [comment]
Sure, I'll do this asap.

**Comment by wokier** [comment]
You might use something like this one
https://upsource.jetbrains.com/idea-ce/file/idea-ce-4f9b5f89b2a19ce700b1373a465c16b28ed8ad52/platform/icons/src/fileTypes/json.svg
Maybe replacing the accolade grey color with the avro blue color
https://avro.apache.org/docs/1.8.2/images/avro-logo.png
Thanks

**Comment by jonathanlermitage** [comment]
Thx,

I tried this:
![preview](https://tof.cx/images/2019/06/11/84272553138d6895de8169a80bccdf3b.png)

If you agree, I will use this version.

**Comment by wokier** [comment]
Great

**Comment by jonathanlermitage** [comment]
Done in 72f3b85cb34ad5a347a7d44ff9d984892fbebf9d

I will probably release 1.6.0 this weekend.
