### ISSUE TITLE
Icon Replacement Issue in IntelliJ IDEA 2023.1.3 when using the New UI

### ISSUE THREAD

**Issue by fronskyofficial** [jonathanlermitage/intellij-extra-icons-plugin#143]
# Issue Description

I am experiencing an issue with the IntelliJ IDEA 2023.1.3 IDE and when using the new UI. The problem is that when using the new UI, the icons provided by the plugin are not replacing the default icons from JetBrains. I have installed IntelliJ using the JetBrains Toolbox. I have tried applying the theme for new UI files to old, but I do not see any changes even after multiple restarts of the IDE and my computer.

# Issue Details

- **Plugin Version:** 2023.2.6-231 <br />
- **OS and IDE Version:** <br />
    - **OS:** Windows 11 Pro 22H2 *(OS Build 22631.1906)* <br />
    - **IDE:** IntelliJ IDEA 2023.1.3

**Comment by jonathanlermitage** [comment]
Hi,  
for now, we can't customize IDE icons when the new UI is enabled.  _Extra ToolWindow Colorful Icons_ plugin has the exact same problem. It seems to be a bug or a regression in the IDE. I opened an issue for that https://youtrack.jetbrains.com/issue/IDEA-321006  
I'm trying to find a workaround, but haven't made any progress yet 😅 😅

**Comment by fronskyofficial** [comment]
This issue seems to be fixed in the 2023.2 version of intellij.
