### ISSUE TITLE
Plugin not functional with Gateway

### ISSUE THREAD

**Issue by devpikachu** [jonathanlermitage/intellij-extra-icons-plugin#152]
## Issues

Plugin not functional for remote development through Jetbrains Gateway, as the VCS plugin is disabled on the client when in this mode. I'm not entirely sure why the plugin depends on VCS.

* **Plugin Version:**  2023.2.9-231
* **OS and IDE Version:**
```
JetBrains Client 2023.2
Build #JBC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.4.11-200.fc38.x86_64
Controller in Remote Development (GO), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    suggest.all.run.configurations.from.context=true
    debugger.new.tool.window.layout=true
    debugger.valueTooltipAutoShowOnSelection=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    org.intellij.plugins.hcl (232.8660.88)
    izhangzhihao.rainbow.brackets (2023.3.3)
    com.intellij.plugins.colorful.darcula.colorscheme (232.8660.88)
    com.intellij.plugins.vscodekeymap (232.8660.88)
    com.intellij.plugins.monokai.colorscheme (232.8660.88)

Current Desktop: KDE
```
* **IDE Logs:** [idea.log](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12429584/idea.log)

**Comment by jonathanlermitage** [comment]
Hi, it depends on the VCS module because I want to customize icons in the VCS toolwindows (Git, etc.).  
I have to admit, I did not try the plugin with the Gateway 😁. I will build a package without the VCS dependency and I will upload this build for a try.

**Comment by jonathanlermitage** [comment]
Hum, it seems that the VCS module is no longer needed. I can override icons in the VCS views without it. I will publish the 2023.2.10 plugin release very soon.

**Comment by jonathanlermitage** [comment]
Here is a fixed build. Can you say me if it works better? Thanks! 
-> 
[Extra Icons-2023.2.9-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12430060/Extra.Icons-2023.2.9-231.zip)

**Comment by devpikachu** [comment]
Thanks for the quick update! I tested it, and now the plugin manager interface shows it as loaded & enabled, but the icons aren't being changed.

There seems to be a `java.lang.NoClassDefFoundError: org/intellij/lang/regexp/RegExpFileType` exception (line 6219 of the log file): [idea.log](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12430145/idea.log)

**Comment by jonathanlermitage** [comment]
Thanks! I see, I will have to remove the Lang module too. This is ok, this is only used to offer syntax highlighting for regular expression fields.

**Comment by jonathanlermitage** [comment]
It should be better now: 
[Extra Icons-2023.2.9-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12430299/Extra.Icons-2023.2.9-231.zip)

**Comment by jonathanlermitage** [comment]
Thanks! I will try with Gateway.

**Comment by devpikachu** [comment]
If you need a remote environment to connect to via Gateway, let me know and I can provision you a mock environment for testing

**Comment by jonathanlermitage** [comment]
Thx! I just tested in a Linux VM with VirtualBox. 
- icons override does not work when plugin is installed in **Client**
- it works better when plugin is installed in **Host**. Meanwhile, the plugin's settings panel is a bit broken, and some icons are too big (PNG icons, but I have plans to migrate all these remaining icons to SVG, which works better). I will fix this later.

![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/ee104caf-11c8-45c3-a854-9613f4702ec7)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/0710b3a4-2fd7-48a2-bc09-89a98d6c2137)

Does it work for you when plugin is installed in Host?

**Comment by devpikachu** [comment]
I just tested this by enabling it on the remote backend and disabling it on the client, and it worked without a hitch, barring the icon issues you've already noticed.

It also seems like having the plugin installed both client-side and host-side has no issues, which is great for those that use settings sync across their editors.

The only remaining issue is that the backend is not picking up my license for the plugin, but I'll be reaching out to JetBrains support for that as I'm fairly certain this is not a flaw with the plugin itself.

I'll post any updates I receive on this thread.

Once again, many thanks for the very prompt investigation and iteration on this issue!

**Comment by jonathanlermitage** [comment]
Thx!  
For now, you can use this release -> [Extra Icons-2023.2.9-231-no-license.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12431094/Extra.Icons-2023.2.9-231-no-license.zip)

It requires no licence . If you want to rebuild this package, you can checkout this project, then run `make buildfree`. The new package is located in `build/distributions/`.

**Comment by devpikachu** [comment]
Just leaving an update here for anyone else that might stumble across this issue. It's a known issue with JetBrains, affecting all IDEs.

https://youtrack.jetbrains.com/issue/GTW-5889/Cannot-Register-Plugin

It seems like the plugin functionality isn't disabled, it just reports weirdly.
