### ISSUE TITLE
user icon scaling is blurry when > 1

### ISSUE THREAD

**Issue by jonathanlermitage** [jonathanlermitage/intellij-extra-icons-plugin#156]
From https://plugins.jetbrains.com/plugin/11058-extra-icons/reviews
> ... However, I've encountered a problem. In the 'Advanced' interface, when I changed the icon size from '1.0' to '2.0', the icons did indeed become larger, but they also became blurry. This has left me puzzled. Why would SVG format images become blurry when enlarged?
>(I intend to place two icons side by side.)"

**Comment by jonathanlermitage** [comment]
An example with a 2x scaling
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/4ebbc04f-6394-4639-8c53-9c6bf5e62ff8)

**Comment by jonathanlermitage** [comment]
For info, the JetBrains API can load an SVG icon from the plugin's resources, and from an Image object, but, AFAIK, there is no API that takes a bytearray or a File.  
That means I have to load user icons and create an Image (thx to JSVG, previously via Apache Batik), then the JetBrains API loads it, and I can invoke a rescale.  
Unfortunately, it produces a blurry image. I asked some help on a JetBrains Slack channel.  
For now, I am blocked. I looked a IntelliJ Community source code a long time ago (when I started to work on Extra Icons, I think ~5 years ago). I will see if I get more chances now.

**Comment by hzau-kuo-jiang** [comment]
Currently, my solution is to simply enlarge the icon by 1.5 times, and at this scale, the blurriness of the icon remains within an acceptable range. I've also decided to abandon the initial idea of placing two icons side by side and instead stack them (implemented in the SVG code). The size of the small icon on top is approximately 12/16 of the background large icon. The result is quite satisfactory.

However, I regret that I cannot provide you with the stacked icons I'm using because they were collected from the internet rather than being my original creations. This might pose copyright issues. 😂

-- Translated by gpt-3.5


目前我的解决方法是 只将图标放大 1.5 倍,这时图标的模糊程度还在可接受的范围内.
同时,不再采取最初的想法--将2个图标并排摆放.
而是将它们堆叠起来(在svg代码中实现).
上面的小图标的大小约为背景大图标的12/16.
这时的效果还不错.
不过,很遗憾,我并不能提供给你 我正在使用的 层叠图标.
因为,它们是我在网络上收集而来的.而非我自己原创.
所以,可能会带来版权上的麻烦.😂

**Comment by jonathanlermitage** [comment]
Hi @hzau-kuo-jiang 
Can you please try this build [Extra Icons-2023.2.10-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643201/Extra.Icons-2023.2.10-231.zip) ?  
I am now using JetBrains API in order to load user SVG files. Files are exported as tmp files (in /tmp) and I load these files as resources via `file://...` (or `file:/...` on windows). I still have some scaling issues on Windows, but I would like to see if it's a bit better on your computer.  
If you confirm this issue, I will raise a ticket on JetBrains' YouTrack, as it should be an issue with their API.  
Thx.

**Comment by jonathanlermitage** [comment]
Some improvements with this build: 
[Extra Icons-2023.2.10-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643281/Extra.Icons-2023.2.10-231.zip):  
- for 16x16 SVG icons, AND if the scaling factor is 1 or 2, it should not be blurry. The IDE handles the scaling for us
- for smaller icons (ex: 8x8): the icon will be blurry. A workaround is to rework the SVG file: open it as a text file and change the width and height attributes to `width="16" height="16"`, then do some rework with an SVG editor (ex: Inkscape)
- for bigger icons (ex: 128x128): the scaling should work better  
I did some tests with these SVG files on Linux, with 1, 1.75 and 2 scaling factor (same value as the display's global scale), and the result was pretty good. 
![8](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/afac542e-6aac-4c58-a00e-ebc7cb31bd08)
![16](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/8c8e630c-cc07-4104-b05f-ed8975a70c14)
![128](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/7a444f5c-3d69-4f7b-b03b-a04284889836)

**Comment by hzau-kuo-jiang** [comment]
> Hi @hzau-kuo-jiang Can you please try this build [Extra Icons-2023.2.10-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643201/Extra.Icons-2023.2.10-231.zip) ? I am now using JetBrains API in order to load user SVG files. Files are exported as tmp files (in /tmp) and I load these files as resources via `file://...` (or `file:/...` on windows). I still have some scaling issues on Windows, but I would like to see if it's a bit better on your computer. Thx.

"I can sense that you are a responsible person. However, at the moment, my abilities do not extend to fulfilling the request you mentioned because I don't even know how to run a JAR file. So far, my capabilities are limited to writing some basic React code, and I have only taken introductory-level Java courses. 😂"

-- Translated by gpt-3.5

我可以感受到你是一位有责任心的人.
不过,目前我的能力并不能做到你所提出的请求.
因为我都不知道怎么运行jar包.
(目前为止,我的能力只够写点简单的react代码,java也只看过入门级的课程😂)

**Comment by jonathanlermitage** [comment]
No problem, you can go to File > Settings > Plugins > click on the wheel, then Install from disk, and select the ZIP file  
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/17b9ce8e-afd1-4a7e-b580-72ed8b8760de)

**Comment by jonathanlermitage** [comment]
I have a new build 
[Extra Icons-2023.2.10-231-no-license.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643516/Extra.Icons-2023.2.10-231-no-license.zip)
This time, I think I handle most cases.  
  
- for 16x16 SVG icons, it should not be blurry. This is the ideal situation
- for smaller icons (ex: 8x8): the icon will be blurry. A workaround is to rework the SVG file: open it as a text file and change the width and height attributes to `width="16" height="16"`, then do some rework with an SVG editor (ex: Inkscape)
- for bigger icons (ex: 128x128): the scaling should work better  

I did some tests with these SVG files (8x8, 16x16 and 128x128) 
![8](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/a3750974-80b1-4166-8ccd-7eadd62462ff)
![16](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/5909d930-8dde-4558-8bb1-47824a5f264c)
![128](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/8215dc30-4636-4bbe-a143-a0cb85dcd2c8)

**Comment by hzau-kuo-jiang** [comment]
> Some improvements with this build: [Extra Icons-2023.2.10-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643281/Extra.Icons-2023.2.10-231.zip):
> 
> * for 16x16 SVG icons, AND if the scaling factor is 1 or 2, it should not be blurry. The IDE handles the scaling for us. This is the ideal situation
> * for smaller icons (ex: 8x8): the icon will be blurry. A workaround is to rework the SVG file: open it as a text file and change the width and height attributes to `width="16" height="16"`, then do some rework with an SVG editor (ex: Inkscape)
> * for bigger icons (ex: 128x128): the scaling should work better
>   I did some tests with these SVG files on Linux (Arch/KDE), with 1, 1.75 and 2 scaling factor (same value as the display's global scale), and the result was pretty good.
>   <img alt="8" width="8" height="8" src="https://user-images.githubusercontent.com/857535/268516281-afac542e-6aac-4c58-a00e-ebc7cb31bd08.svg">
>   <img alt="16" width="16" height="16" src="https://user-images.githubusercontent.com/857535/268516284-8c8e630c-cc07-4104-b05f-ed8975a70c14.svg">
>   ![128](https://user-images.githubusercontent.com/857535/268516285-7a444f5c-3d69-4f7b-b03b-a04284889836.svg)

[](url)"You have succeeded, although there may be some details that need to be perfected. But the latest version of the plugin has already implemented the functionality I need."

-- Translated by gpt-3.5

你成功做到了,虽然可能还有一些细节的地方需要完善.
但最新版的插件,已经实现了我所需要的功能了.

![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/f3a998c8-47c0-428c-92fd-11153caef78b)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/b83de74a-f3c9-410d-9ec6-9246ec6a7d23)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/92ab4188-1229-44bc-a3d8-ccc5d3968714)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/c9e4f737-259a-4855-a311-e5eb3d5a6cb0)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/06344f26-8d4a-4d9f-80bb-c61d759455e2)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/35641c35-a99b-4adf-a9c5-47a62b565e88)
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/fc62fa7b-a1a1-480e-a885-218dc6b7e938)

**Comment by hzau-kuo-jiang** [comment]
> I have a new build [Extra Icons-2023.2.10-231-no-license.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643516/Extra.Icons-2023.2.10-231-no-license.zip) This time, I think I handle most cases.
> 
> * for 16x16 SVG icons, it should not be blurry. This is the ideal situation
> * for smaller icons (ex: 8x8): the icon will be blurry. A workaround is to rework the SVG file: open it as a text file and change the width and height attributes to `width="16" height="16"`, then do some rework with an SVG editor (ex: Inkscape)
> * for bigger icons (ex: 128x128): the scaling should work better
> 
> I did some tests with these SVG files (8x8, 16x16 and 128x128) and 1, 1.25, 1.5, 1.57 and 2 scaling ratios. The 8x8 file is blurry (but it can be manually fixed), and 16x16 and 128x128 files rendering is perfect on my machine. ![8](https://user-images.githubusercontent.com/857535/268522841-a3750974-80b1-4166-8ccd-7eadd62462ff.svg) ![16](https://user-images.githubusercontent.com/857535/268522842-5909d930-8dde-4558-8bb1-47824a5f264c.svg) ![128](https://user-images.githubusercontent.com/857535/268522843-8215dc30-4636-4bbe-a143-a0cb85dcd2c8.svg)

我也尝试了这款,
至少对我来说,这款也同样实现了令我满意的效果.
非常期待 (jetbrians 的应用商店里)下一个版本的插件 包含了 这一 "无损放大" 特性.

![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/98842618/bc031c53-e540-4e93-8889-39523f35bef6)

😊

**Comment by hzau-kuo-jiang** [comment]
> > I have a new build [Extra Icons-2023.2.10-231-no-license.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12643516/Extra.Icons-2023.2.10-231-no-license.zip) This time, I think I handle most cases.
> > 
> > * for 16x16 SVG icons, it should not be blurry. This is the ideal situation
> > * for smaller icons (ex: 8x8): the icon will be blurry. A workaround is to rework the SVG file: open it as a text file and change the width and height attributes to `width="16" height="16"`, then do some rework with an SVG editor (ex: Inkscape)
> > * for bigger icons (ex: 128x128): the scaling should work better
> > 
> > I did some tests with these SVG files (8x8, 16x16 and 128x128) and 1, 1.25, 1.5, 1.57 and 2 scaling ratios. The 8x8 file is blurry (but it can be manually fixed), and 16x16 and 128x128 files rendering is perfect on my machine. ![8](https://user-images.githubusercontent.com/857535/268522841-a3750974-80b1-4166-8ccd-7eadd62462ff.svg) ![16](https://user-images.githubusercontent.com/857535/268522842-5909d930-8dde-4558-8bb1-47824a5f264c.svg) ![128](https://user-images.githubusercontent.com/857535/268522843-8215dc30-4636-4bbe-a143-a0cb85dcd2c8.svg)
> 
> 我也尝试了这款, 至少对我来说,这款也同样实现了令我满意的效果. 非常期待 (jetbrians 的应用商店里)下一个版本的插件 包含了 这一 "无损放大" 特性.
> 
> ![image](https://user-images.githubusercontent.com/98842618/268523969-bc031c53-e540-4e93-8889-39523f35bef6.png)
> 
> 😊

"I also tried this one, and at least for me, it achieved the desired results. I'm really looking forward to the next version of the plugin in the JetBrains App Store, which includes this 'lossless scaling' feature."

-- Translated by gpt-3.5

So sleepy that I forgot to "speak English "(now 3:41am 😂)

**Comment by jonathanlermitage** [comment]
No problem, DeepL is my friend 😁

**Comment by hzau-kuo-jiang** [comment]
> No problem, [DeepL](https://www.deepl.com/translator) is my friend 😁

🤣
