### ISSUE TITLE
Icon size issues

### ISSUE THREAD

**Issue by raubv0gel** [jonathanlermitage/intellij-extra-icons-plugin#164]
## Issues

I have set custom **SVG** icons to several paths

![grafik](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/9824146/8fc20f01-f946-4faa-8326-edb0be61b138)

In latest PhpStorm and Extra Icon plugin there are sizing issues:

![grafik](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/9824146/b8b3a375-8d45-4a92-a6c1-72cb8af7ffe4)

![grafik](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/9824146/11fa29af-e59a-4f52-8dab-e494c91470a4)

![grafik](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/9824146/36d45862-fd9e-4630-a462-1726e468705a)

(The bar hight is bigger with custom icon shown. It’s „jumping“.)

**I’m using a 4K high PPI display.**

PhpStorm 2023.2.3
Build #PS-232.10072.32, built on October 13, 2023
You have a perpetual fallback license for this version.
Subscription is active until July 6, 2025.
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Jenkins Plugin 0.13.19-2023.2
GC: G1 Young Generation, G1 Old Generation
Memory: 12288M
Cores: 32
Registry:
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    Batch Scripts Support (1.0.13)
    com.github.copilot (1.3.2.3479)
    com.github.mikesafonov.jenkins-linter-idea-plugin (0.6.0)
    com.intellij.ideolog (222.1.0.0)
    com.crunch42.openapi (1.66)
    Statistic (4.2.7)
    com.intellij.properties (232.8660.88)
    String Manipulation (9.11.3)
    Jenkins Control Plugin (0.13.19-2023.2)
    lermitage.intellij.extra.icons (2023.2.12-231)
    com.intellij.ml.llm (232.9826)
    zielu.gittoolbox (500.0.21+222)
    mobi.hsz.idea.gitignore (4.5.2)
    com.intellij.plugins.html.instantEditing (232.8660.142)
    izhangzhihao.rainbow.brackets (2023.3.6)
    org.exbin.deltahex.intellij (0.2.8.1)
    com.falconiform.LanguageTools (1.1-DEV)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
    de.espend.idea.php.annotation (9.4.0)
    com.kalessil.phpStorm.phpInspectionsUltimate-mp (2023.1)
    de.espend.idea.php.phpunit (7.1)

**Comment by jonathanlermitage** [comment]
Hi @raubv0gel, 
changing the UI Scale Factor may help: 
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/92120584-db53-4672-96a7-87b57f7b52c9)

Otherwise, as a workaround, SVG icons should have these attributes: `width="16" height="16"`. This is the ideal situation. If the width or height have higher values, the plugin has to resize and scale the icon.

**Comment by raubv0gel** [comment]
@jonathanlermitage, thank you! The scale factor 1.0 seems to be the optimum in my case (1.5 was detected automatically). Maybe some thing is wrong if

![grafik](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/9824146/3c391732-91de-4d82-b594-81e436250cf9)

is set? I guess, I did not have this issue on a FHD display with scaling set to 100 %.

**Comment by jonathanlermitage** [comment]
Thx for your feedback! 😎  
Yeah, these scaling issues are a nightmare. Unfortunately, I no longer have a 4K display, so I can't easily test my fixes. Things should go better next year (I'll invest in a new laptop 🥳).  
For now, I can only say things differ when you're on Linux/X vs Linux/Wayland vs macOS vs Windows, 1080p vs 4K, fractional scaling enabled vs disabled.  
At least, I am happy to see the `Additional UI Scale Factor` can help some users.

**Comment by raubv0gel** [comment]
If you want, I can do the tests. I’ve some experience in IDEA plugin development. You could give me some hints where to look in your source code or you create a branch containing your fix ideas. ¯\_(ツ)_/¯

Anyway, for the moment, I’m glad that `Additional UI Scale Factor` works around the problem.
