### ISSUE TITLE
User Icons > Directory does not work

### ISSUE THREAD

**Issue by Schwepsi** [jonathanlermitage/intellij-extra-icons-plugin#170]
Plugin Version: 2023.3-231 Trial
<details><summary>OS & PHP-Storm</summary>
PhpStorm 2023.2.3
Build #PS-232.10072.32, built on October 13, 2023
[...]
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-10008-tuxedo
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.ideolog (222.1.0.0)
    lermitage.intellij.extra.icons (2023.3-231)
    ru.adelf.idea.dotenv (2023.2)
    de.espend.idea.php.annotation (9.4.0)
    izhangzhihao.rainbow.brackets (2023.3.7)
    fr.adrienbrault.idea.symfony2plugin (2022.1.259)
    de.php_perfect.intellij.ddev (1.1.1)

Current Desktop: KDE
</details>

the log seems not to show something interesting and is ~330 lines and is more than the allowed 65536 chars...

Most interesting are the InterruptedException from the DDEV Plugin (but was expected) and the com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection$VFSCorruptedException (was also expected, because I invalidated the caches)

---
Perhaps I am missing something, but could not find anything in the documentation.

I tried to set an icon for the 'Command' Directory, but it shows the normal one, even after clearing all caches and the restart.

I reduced to the minimal possible setting:
User Icon > Add
Description: Command
Type: Directory
Icon Pack Name: empty
Icon: bundled: bash.svg

Edit Condition >
Names: Command (also tried src/Command)
(*) Equals

In Main Menu > File > Invalidate Caches
Selected all checkboxes and pressed 'Invalidate and Restart'

After Restart the plugin setting is saved, but the icon is the normal one

**Comment by jonathanlermitage** [comment]
Hi,
can you please add a screenshot? I'm not sure to see what is the 'Command' directory exactly.  
Thanks!

**Comment by jonathanlermitage** [comment]
Hoo, I think I understand why it doesn't work. File and folder paths are lowercased before checks. Please type "command" instead of "Command".  
I will fix that in a future release. I should automatically lowercase user inputs (except for regex).

**Comment by Schwepsi** [comment]
Yes, this works.

Thanks, and I am blind... Reading the help text in the edit condition panels tells that that the path is lowercased...


During further testing today I noticed that the 'Test your Model' function has problems.
Parent: src
Name: Equal "command"
Test your model: src/command <- has a red box
In the "Project Files" view it works as intended and the icon is set to src/Command. If a second issue is wished, just tell me

**Comment by jonathanlermitage** [comment]
Hi @Schwepsi !  
Can you please test this build [Extra Icons-2023.3-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/13328179/Extra.Icons-2023.3-231.zip) ?  
Now, when you register a model, conditions (except for regex and Facets) are automatically lower-cased.
