### ISSUE TITLE
No prettier icon on mjs configs

### ISSUE THREAD

**Issue by bielarusajed** [jonathanlermitage/intellij-extra-icons-plugin#174]
## Issues

* the **plugin version**: 2023.4.2
* the **OS and IDE version**: WebStorm 2023.3, Build #WS-233.11799.229, built on December 1, 2023, macOS 14.0

Plugin doesn't have built-in icons for `prettier.config.mjs` and `.prettirrc.mjs`, but it's one of the default config names, according to the prettier docs:

<img width="282" alt="image" src="https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/90352332/8ba547de-64d5-4271-9e90-c8b2b77bc5d8">
<img width="804" alt="image" src="https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/90352332/219f12bc-a6c2-4060-a806-a37fb5e9bc44">

**Comment by jonathanlermitage** [comment]
Thanks! I will add this asap.

**Comment by jonathanlermitage** [comment]
Fixed. Will be part of the upcoming next release.
