### ISSUE TITLE
Please add some new ICONS

### ISSUE THREAD

**Issue by ZHOUXING1997** [jonathanlermitage/intellij-extra-icons-plugin#177]
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/33240857/1203e962-13db-4cce-a502-3cc61946f7c4)

Three gray ICONS

**Comment by jonathanlermitage** [comment]
Please open an issue here: https://github.com/jonathanlermitage/intellij-extra-toolwindow-colorful-icons/issues
