### ISSUE TITLE
Apply icon to files only

### ISSUE THREAD

**Issue by thencke** [jonathanlermitage/intellij-extra-icons-plugin#183]
## Issues

Please describe the issue:

I created a custom icon for a specific path and it works well, however the icon is also being aplied to the class, methods, properties from the file as shown in the screenshot below

![image](https://github.com/user-attachments/assets/a5fe2166-9609-4300-8564-cfd79d2dcdcc)

How it was:

![image](https://github.com/user-attachments/assets/a35ded05-3b4b-4529-976f-6235028cbdf7)

Is there a way to apply the icon only to the file?

* the **plugin version**
2024.6.2
* the **OS and IDE version**. Open your IDE and go to <kbd>Help</kbd>, <kbd>About</kbd>, then <kbd>Copy</kbd>
PyCharm 2024.1.1 (Professional Edition)
Build #PY-241.15989.155, built on April 29, 2024
Licensed to ---
Subscription is active until December 15, 2024.
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  Dummy Text Generator (1.2.0)
  com.github.catppuccin.jetbrains (3.3.1)
  com.markskelton.one-dark-theme (5.11.0)
  String Manipulation (9.14.1)
  lermitage.intellij.extra.icons (2024.6.2)
  name.kropp.intellij.makefile (241.14494.150)
  com.jetbrains.space (241.15989.9)
  com.mallowigi (97.0.0)
  mobi.hsz.idea.gitignore (4.5.3)
  com.github.copilot (1.5.15.6094)
  com.github.inxilpro.intellijalpine (v0.4.2)
  com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.15.0)

* the **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Show Log in Explorer</kbd>, then attach `idea.log` 
idea.log

* the **stacktrace**, if any
* any useful information: **what did you do just before or during the issue**, etc.

:warning: This information is needed in order to determine if this is an IDE bug or a plugin bug, and to find a solution or a workaround.

**Comment by jonathanlermitage** [comment]
Hi @thencke , can you please share how you registered this icon?  
A screen like this:  
![image](https://github.com/user-attachments/assets/64ce646e-627f-48a6-84b6-fd4b0561c735)

**Comment by thencke** [comment]
Hi @jonathanlermitage ,

Of course, please see below

![image](https://github.com/user-attachments/assets/12e00358-0629-46cb-bfa5-60805fea5401)

**Comment by jonathanlermitage** [comment]
Thank you very much. I reproduced this issue on my machine. I will provide a fix for the next plugin release.

**Comment by jonathanlermitage** [comment]
@thencke  I just packaged a new version. Now, nested objects should not have a custom icon. I tried with Java classes, but it should also work with Python. Can you please tell me if this better? 
[Extra Icons-2024.6.3.zip](https://github.com/user-attachments/files/16352151/Extra.Icons-2024.6.3.zip)

**Comment by thencke** [comment]
@jonathanlermitage 
Thanks for your time,
I could not see any plugin updates in the pycharm marketplace, you attached this zip file in your comment but I am not sure what to do with it

**Comment by thencke** [comment]
Oh nevermind, already figure out, I just installed the plugin but it seems to not work yet

![image](https://github.com/user-attachments/assets/7eef6532-8850-433e-8031-cda957570be6)

![image](https://github.com/user-attachments/assets/f13f9f48-ea79-4254-a634-f3dd8ab0ffe2)

I think this is the version (2024.6.3) you shipped in that zip file, no?

**Comment by jonathanlermitage** [comment]
Yeah, to install this release, please go to `File` > `Settings` > `Plugins` > click on the wheel icon > `Install plugin from disk`, then pick the zip file.  
You may have seen a plugin upgrade from the marketplace, but this is a different build, even if both releases are labeled as 2024.6.3. Sry for the confusion ^^.  

I will try with Python files.  
BTW, do you have a sample project or just a sample python file to share? It would help me a lot. Thx.

**Comment by thencke** [comment]
I installed your zip file directly.
Here is a simple project with a similar file structure I am using.
Using the regex rule from my custom icon also has the same effect in this tiny project

[IconDemoProject.zip](https://github.com/user-attachments/files/16356211/IconDemoProject.zip)

**Comment by jonathanlermitage** [comment]
Thank you very much for this sample project. It helped me a lot.  
This issue should be fixed now. I packaged a new plugin file: [Extra Icons-2024.6.3.zip](https://github.com/user-attachments/files/16361735/Extra.Icons-2024.6.3.zip)

**Comment by thencke** [comment]
Perfect! worked like a charm, thank you!
