### ISSUE TITLE
requirements.txt icon is not working

### ISSUE THREAD

**Issue by schr1k** [jonathanlermitage/intellij-extra-icons-plugin#185]
* **Plugin version**: 2024.6.3
* **OS and IDE version**: PyCharm 2024.1.4 (Professional Edition) Build #PY-241.18034.82, built on June 24, 2024
* **IDE logs**: [idea.log](https://github.com/user-attachments/files/16394377/idea.log)

`requirements.txt` icon is not working

![image](https://github.com/user-attachments/assets/bcd1a254-5a85-4b09-8f3f-ce1849f0eee5)

I fixed it by adding custom icon, but thought this information will be useful for u

![image](https://github.com/user-attachments/assets/938dfdba-365d-442c-923b-697c32a9aade)

Also will be great to have both *.yml and *.yaml files supported by default (workflows, docker compose and other tools)

**Comment by jonathanlermitage** [comment]
Hi @schr1k, can you please share the relative path of the `requirements.txt` file (relative to the project's root)?  

Also, do you see the other Helm icons? If not, that would mean Extra Icons failed to detect your Helm files. Basically, I consider a folder is a Helm folder if it contains a `Chart.yaml` or `values.yaml` file (or both). But my assertion may be wrong, and I may need to rework this logic.

**Comment by jonathanlermitage** [comment]
OMG, don't mind, I support only `requirements.yaml`, not `requirements.txt`. I will add support for requirements.txt too 😅 Sorry for that.

**Comment by jonathanlermitage** [comment]
Thanks for this report. I expected to see the Python facet in Python projects, but it doesn't work super well, especially on PyCharm. This is why you didn't see the icon for `requirements.txt` files. I will fix that asap.

> Also will be great to have both *.yml and *.yaml files supported by default (workflows, docker compose and other tools)

Sure!

**Comment by jonathanlermitage** [comment]
I just packaged a version with better `requirements.txt` support: [Extra Icons-2024.6.3.zip](https://github.com/user-attachments/files/16396873/Extra.Icons-2024.6.3.zip). Can you please tell me if this is OK for you?  
To install this package, go to File > Settings > Plugins > the wheel icon > Install plugin from disk.

This package also supports yaml files for github workflows. For Docker (dockercompose, dockerfile...), it should already be ok.

**Comment by schr1k** [comment]
Works like magic, thanks a lot
