### ISSUE TITLE
Not display docker-compoce icons in Rider

### ISSUE THREAD

**Issue by denis-peshkov** [jonathanlermitage/intellij-extra-icons-plugin#187]
## Issues

Please describe the issue:

* the **plugin version 2024.6.4**

JetBrains Rider 2024.1.5
Build #RD-241.18968.19, built on August 2, 2024
Licensed to Denis Peshkov
You have a perpetual fallback license for this version.
Subscription is active until April 10, 2025.
Runtime version: 17.0.11+1-b1207.30 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  me.dench327.plugins.usinglocator (1.0.3)
  com.github.exidcuter.dockerregistryexplorer (1.1.0-stable)
  nsubstitutecomplete-rider (2024.1.2)
  fr.socolin.application-insights-debug-log-viewer (2024.1.2)
  lermitage.intellij.extra.icons (2024.6.4)
  Abc.MoqComplete.Rider (2024.1.1.1)
  com.wakatime.intellij.plugin (15.0.1)
  com.intellij.resharper.StructuredLogging (2024.1.4.331)
  com.intellij.plugin.adernov.powershell (2.6.1)
  ru.adelf.idea.dotenv (2024.1)
  org.sonarlint.idea (10.8.0.79133)
  com.microsoft.vso.idea (1.162.2)
  com.intellij.resharper.azure (3.50.0.1784-2024.1)

[idea.log](https://github.com/user-attachments/files/16623031/idea.log)

:warning: This information is needed in order to determine if this is an IDE bug or a plugin bug, and to find a solution or a workaround.

## Feature requests

![image](https://github.com/user-attachments/assets/0d5c89fe-e93d-4651-9b53-b06275855e2e)

* few version ago it was working fine, now not display icons for docker-compoce.yml and docker-compoce.override.yml
* before it works with by default
* now not work and can't override even by custom rules

**Comment by jonathanlermitage** [comment]
@denis-peshkov  I tested with Rider 2024.2 and 2024.1.6 (which is very new) and it works fine. Can you please upgrade your IDE from 2024.1.5 to 2024.1.6 and see if this issue is solved? Thanks!

**Comment by jonathanlermitage** [comment]
Ho wait, don't mind, this is an issue with nested files. This is a very specific issue.  
Some people didn't want to see a custom icon for nested files, and this explains why you see a custom icon for the parent docker-compose file, and not the nested files.  
I think I should simply offer a way to activate and deactivate the icon override for nested files.

Just to be sure, can you please send me a sample docker-compose file? This is the first time I see the IDE displaying nested files for a docker-compose file. Thanks!

**Comment by jonathanlermitage** [comment]
Actually, I would need to reproduce this: 
![image](https://github.com/user-attachments/assets/9111bc7b-06ea-4a1e-9dc7-aa3cb1bb1792)
The parent docker-compose with the custom icon (is it a file or a folder?) plus the nested files with the default icons. Thx.

**Comment by jonathanlermitage** [comment]
BTW, it can be an issue with the Docker plugin. I tried with IJ Ultimate, and I can no longer override icons of file with a name starting with `docker-compose.`. Per example, I can customize `docker-compose-1.yml`, but not `docker-compose.1.yml`. This issue may be more complex, I don't know.

**Comment by jonathanlermitage** [comment]
Feel free to upvote https://youtrack.jetbrains.com/issue/IDEA-358704/Cant-override-some-docker-compose-files-icon
