### ISSUE TITLE
Add support for ESLint v9 and Stylelint config files

### ISSUE THREAD

**Issue by peter-neumann-dev** [jonathanlermitage/intellij-extra-icons-plugin#191]
It would be nice to enable the existing ESLint Icon for `eslint.config.js` as well.

Stylelint config files are not supported yet: https://stylelint.io/user-guide/configure

- stylelint.config.js
- .stylelintrc.js
- stylelint.config.mjs
- .stylelintrc.mjs
- stylelint.config.cjs
- .stylelintrc.cjs
- .stylelintrc.json
- .stylelintrc.yml
- .stylelintrc.yaml
- .stylelintrc

Icon:
<img src="https://github.com/user-attachments/assets/d480d920-c505-493a-9181-e1a1ef9af9a0" width="48em">

Official color according to https://simpleicons.org/?q=stylelint would be `#263238` (but should be white in dark themes i guess)

**Comment by jonathanlermitage** [comment]
Sure. Thanks for these suggestions! I will include them in the upcoming 2024.10.1 plugin release.

**Comment by peter-neumann-dev** [comment]
Thank you very much! 🥳

**Comment by jonathanlermitage** [comment]
New plugin release submitted last Friday. JetBrains should publish it soon.
