### ISSUE TITLE
Custom icons not working in Explorer in Rider for c# project

### ISSUE THREAD

**Issue by htachoires** [jonathanlermitage/intellij-extra-icons-plugin#192]
## Issues

Please describe the issue:

* version: 2024.9.1
* IDE version : Build #RD-243.21565.191

Hello Jonathan,
I'm using your plugin since a few years now and i'm expecting an issue that is not fix yet so I think it would be nice to share it.

I have configured custom icons that worked before and stops working after an update (which I don't know when since It was a long time ago).

The issue i'm facing is that custom icons of type file doesn't work anymore in `Explorer` windows but still in the tab views. I tried to remove and recreate it's not working with c# file

View tab is working :
![image](https://github.com/user-attachments/assets/132844e9-2056-47e4-8b7e-c141bb76d551)

Explorer tab not working :
![image](https://github.com/user-attachments/assets/09671371-06cf-4645-ad70-94fe8b9459df)

The configuration I'm using :
![image](https://github.com/user-attachments/assets/e5def613-af81-469c-93ef-13423b8147f6)

The setting:
![image](https://github.com/user-attachments/assets/533a5058-3960-43ad-820b-7aae0a1f0664)

Regex check : 
![image](https://github.com/user-attachments/assets/998e0450-7023-486c-a6d9-40c16a614aa9)

I tried everything but I can't find a solution alone

Folder for c# project is not working also 

Do you have any idea ?

Thank you,
Hugo

**Comment by jonathanlermitage** [comment]
Hi!

I reproduced this bug.  
It seems that Rider does not allow icon override for `.cs` files, at least with Rider 2024.3, 2024.2.7 and 2024.1.6.  
I will check if there is any workaround for that, otherwise I will raise an issue in JetBrains' bugtracker. This is not the first time JetBrains prevents icon override in the Explorer view.

**Comment by jonathanlermitage** [comment]
I think I found the issue. When overriding file icons, the IDE is supposed to return information about files in the form of a `PsiFile` object. All the IDEs do that, except Rider. It seems to return a `CSharpFile` object.  
I'm testing a workaround.

**Comment by jonathanlermitage** [comment]
@htachoires can you please tell me if this new build works better? -> [Extra Icons-2024.9.1.zip](https://github.com/user-attachments/files/17963731/Extra.Icons-2024.9.1.zip)

Thanks!

**Comment by htachoires** [comment]
Thank you for you fast reaction and fix !

It's working like a charm : 
![image](https://github.com/user-attachments/assets/6e3c48fd-7416-4145-bdd8-cf478b36084e)
