### ISSUE TITLE
Extra icons are not shown in Repositories tool window

### ISSUE THREAD

**Issue by naftalmm** [jonathanlermitage/intellij-extra-icons-plugin#28]
IntelliJ IDEA lets you review the state of your project at a selected revision (more about this feature:
https://www.jetbrains.com/help/idea/investigate-changes.html#review-snapshot-at-revision)

But in the opened tool window with repository files none of the extra icons are shown

![image](https://user-images.githubusercontent.com/10289217/75487819-39690c00-59c0-11ea-8c4e-87cd4b1d60f1.png)

**Comment by Sheigutn** [comment]
Unfortunately I don't think this is possible considering the FileChooserDescriptor#getIcon in RepositoryBrowserPanel doesn't call the IconProvider, only FileType.getIcon() of the FileType it finds: https://github.com/JetBrains/intellij-community/blob/master/platform/vcs-impl/src/com/intellij/openapi/vcs/impl/RepositoryBrowser.kt#L80

**Comment by jonathanlermitage** [comment]
Opened issue https://youtrack.jetbrains.com/issue/IDEA-239724

**Comment by jonathanlermitage** [comment]
@naftalmm @Sheigutn Good news! We should be able to customize icons by implementing `FilePathIconProvider`.  
Unfortunately, this class has been introduced with IJ 2020.1, and I don't want to drop support for users who stick to IJ 2019. I think I will wait IJ 2020.2 release, then update minimal IJ version to 2020.1.

**Comment by jonathanlermitage** [comment]
Implemented in [ide201](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/tree/ide201) branch. It works well, icons are overridden in VCS views (local changes, log).

**Comment by naftalmm** [comment]
Awesome! Thank you!

**Comment by jonathanlermitage** [comment]
I will maintain and publish both master and ide201 branches.
