### ISSUE TITLE
Icons not working - WebStorm 2019.3.3

### ISSUE THREAD

**Issue by nvwebd** [jonathanlermitage/intellij-extra-icons-plugin#29]
Hey.

Would love to get some info on why / how to add the icons to the IDE.

I've tried everything and I can't get them to display on the files.

![icons](https://user-images.githubusercontent.com/10594273/75630449-1d957e00-5beb-11ea-95d2-021272b2ce48.png)
![iconsBreadcrumbs](https://user-images.githubusercontent.com/10594273/75630453-1e2e1480-5beb-11ea-8a58-d4623912b91d.png)

It's funny that the icons seem to be displayed in the breadcrumbs of the IDE, but the project window can't seem to bind the icons to the files.

**Comment by jonathanlermitage** [comment]
Hi,

you seem to use a plugin (Material Theme?) that overrides IDE icons, and Extra Icons plugin probably has a lower priority.

**Comment by nvwebd** [comment]
@jonathanlermitage You're right. Deleting the plugin and setting everything to default helped - with some restarts.

I'll try to get them to work together and post my findings.

Cheers.
