### ISSUE TITLE
IU-193+ compatibility

### ISSUE THREAD

**Issue by jonathanlermitage** [jonathanlermitage/intellij-extra-icons-plugin#30]
![deprecation](https://tof.cx/images/2020/03/15/3d0766996f601f287dbe52fc6a217fe5.png)

**Comment by Sheigutn** [comment]
Apparently there's a new method ImageUtil.createImage, but it's only available in 2019.3 and upwards, so no backwards compatibility.

**Comment by jonathanlermitage** [comment]
finally, some non-deprecated `createImage` methods exist in IJ 183 :-)

Closing this issue.
