### ISSUE TITLE
Markdown file icons are overridden by Markdown Navigator plugin

### ISSUE THREAD

**Issue by volodymyr-gz** [jonathanlermitage/intellij-extra-icons-plugin#32]
Markdown file icons in Project view are overridden by [Markdown Navigator Enhanced plugin](https://plugins.jetbrains.com/plugin/7896-markdown-navigator-enhanced). 

![Screenshot 2020-04-27 at 15 27 42](https://user-images.githubusercontent.com/14126089/80383998-9be96600-88a4-11ea-85da-0a41e09c6db3.png)

Icons are still displayed properly in editor tabs:
![Screenshot 2020-04-27 at 15 28 14](https://user-images.githubusercontent.com/14126089/80384001-9d1a9300-88a4-11ea-8792-2791996e8037.png)

Is there a way to fix it, and have extra icons in Project view as well?

#### Environment
Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
macOS 10.15.3

**Comment by jonathanlermitage** [comment]
I will ask some help to JetBrains support asap. ExtraIcons icon provider has "first" order attributes, so it should work (Markdown Navigator plugin has default order).  
I also tried to implement the FileIconProvider interface (in addition to IconProvider), but it doesn't help.

**Comment by jonathanlermitage** [comment]
Hi @volodymyr-gz, I implemented https://youtrack.jetbrains.com/issue/IDEA-239821 solution. Can you try this build? 
[Extra Icons-1.32.0.183.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/4974552/Extra.Icons-1.32.0.183.zip)
Thx!

**Comment by jonathanlermitage** [comment]
I may be fixed in 1.33. If not, I think the only one solution is to contact the developer of Markdown Navigator plugin in order to tweak IconProvider priority in his project.
