### ISSUE TITLE
Feature: Preset Icon Set for User Icons

### ISSUE THREAD

**Issue by Obiwarn** [jonathanlermitage/intellij-extra-icons-plugin#34]
Show an example icon set to choose from on creating a new user icon. e.g. those from Atom Material Icons Plugin or similar.

I am too lazy to search for all my custom Icons :-)

**Comment by jonathanlermitage** [comment]
I think it would complexify the UI.

Regular users should simply download their favorite icons set and save it to a specific folder.

**Comment by Obiwarn** [comment]
True, but cumbersome for most users who want to quickly add one or two more
icons.

Plus: you have to do this on every machine you sync your Webstorm settings
to (I have three for instance).

Or, at least you let the user choose from your plugin icons?

**Comment by jonathanlermitage** [comment]
Someone could implement https://github.com/jonathanlermitage/intellij-extra-icons-plugin/issues/31 to let users edit the default icons list.
