### ISSUE TITLE
User Icons Regexp needs explanation

### ISSUE THREAD

**Issue by Obiwarn** [jonathanlermitage/intellij-extra-icons-plugin#35]
I couldn't get to run: a file containing "Store" 

I tried all these:
/.*Store.*/    
Store
.*Store.*
*Store*

**Comment by jonathanlermitage** [comment]
It uses [Java regex](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html). I think you should use `.*Store.*`.  

I should probably replace "Regex to ignore..." label by "Regex (Java Pattern) to ignore...".

**Comment by jonathanlermitage** [comment]
@Obiwarn I tried this, is it okay for you?

![](https://tof.cx/images/2020/05/05/6e57441ac1c98d682ae81444493aac9f.png)

**Comment by Obiwarn** [comment]
Great. Thank you.
