### ISSUE TITLE
Add file extension

### ISSUE THREAD

**Issue by yackinn** [jonathanlermitage/intellij-extra-icons-plugin#37]
How do set another user icon with a file extension?

*.facade.ts

The extension set to *.facade.ts won't work.

![screenshot 2020-05-16 um 14 20 56](https://user-images.githubusercontent.com/61085055/82119644-80c19600-9780-11ea-9ede-72021224d0b5.png)

Regex will work but only for extension that don't exist yet.
This works.
^.*\.facade.test$

This won't work.
^.*\.facade.ts$

**Comment by yackinn** [comment]
It's atom material icons plugin that also adds icons. That plugin overwrites all plugins from extra icons. Can we change that behavior and overwrite the other plugins settings?

**Comment by jonathanlermitage** [comment]
Same problem here: https://github.com/jonathanlermitage/intellij-extra-icons-plugin/issues/32  

I don't know how to force Icons Providers priority.  
Submitted https://youtrack.jetbrains.com/issue/IDEA-239821, waiting for assistance.

**Comment by yackinn** [comment]
Thank you. I upvoted the issue.

Can you tell me what's wrong with this setting?
.spec.ts files won't show the correct icon.
The default ts icon is shown.

I've set these settings.
ts files
extensions > .ts

spec files
extensions > .spec.ts

Regex on spec also won't work. ^.*\.spec.ts$
It works on facades though. ^.*\.facade.ts$
