### ISSUE TITLE
[Feature Request] Get composer icons by default

### ISSUE THREAD

**Issue by juanmaa1414** [jonathanlermitage/intellij-extra-icons-plugin#38]
PHP devs would be enormously happy to have Composer (dependencies tool) composer.json and composer.lock icons with the shape of the little composer man logo. Can you add these please?

Thanks for the work. Cheers.

**Comment by jonathanlermitage** [comment]
@juanmaa1414 Sure!   
Could you suggest an SVG icon plz?

**Comment by juanmaa1414** [comment]
Well... I tried to got it by using a converter. If you cannot get it working, I would ask you to try it. Thanks!

[https://drive.google.com/open?id=1OSanZeo56NeuAF-L3ehln_-vDky48wKr](File on Google Drive)

**Comment by jonathanlermitage** [comment]
Thx!

Implemented in 0ca3d461df35cd96928ba70ad242b7a99e0c5cb7
