### ISSUE TITLE
Settings panel

### ISSUE THREAD

**Issue by lppedd** [jonathanlermitage/intellij-extra-icons-plugin#4]
Being the amount of icons will grow over time, a setting panel is a must-have.
This is the state of my current implementation, using the same Swing style of the "Gutter Icons" one, to maintain consistency.
Groups are ordered by name (ascending).

Required changes:
- Search contributor
- `BaseIconProvider `will expose a new attribute `name` or `description`
(need to find a better name for the class)
- `Model` class will expose a new attribute `name` (maybe a better name would be `IconModel`)

![image](https://user-images.githubusercontent.com/19871649/49342275-f2c02100-f659-11e8-9c0f-08623ecb0aea.png)

**Comment by lppedd** [comment]
@jonathanlermitage I will push the code tomorrow in a separate branch in my fork

**Comment by lppedd** [comment]
Sorry I've been busy. Gonna finish it on saturday

**Comment by jonathanlermitage** [comment]
No problem, there's no deadline :-D

**Comment by jonathanlermitage** [comment]
@lppedd Could you push your code to your branch? I'd like to try to finish the Settings Panel. 
Thx!

**Comment by jonathanlermitage** [comment]
@lppedd could you share the code of your JTable? I have implemented settings persistence, and I'd like to reuse your work to finalize the graphical Settings Panel. Thx ;-)

**Comment by jonathanlermitage** [comment]
finally, I'm doing it.
