### ISSUE TITLE
User icons location

### ISSUE THREAD

**Issue by amstiel** [jonathanlermitage/intellij-extra-icons-plugin#41]
Where plugin stores "User icons" settings? Is there any possibility to share/backup my "User icons"? Or even import "User icons" json/xml file, not icon by icon.
After last update my settings with user icons were reset to default, just want to avoid it in future 🙃.

P.S. Thanks for the plugin.

**Comment by jonathanlermitage** [comment]
Thx @amstiel! 

Settings are stored in IDE's config folder (in `config/options/lermitage-extra-icons.xml`). 
While exporting IDE settings, you should see a `ExtraIconsSettings` checkbox: 
![extraicons-settings-export](https://user-images.githubusercontent.com/857535/100021475-d5a23100-2de1-11eb-8ced-5f4db75744dd.png)
To find IDE's config folder, please see https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs.


Project-level settings are stored in project's folder (`.idea/ij-extra-icons.iml`).

**Comment by amstiel** [comment]
Thx for answer! 

So, any plans for ability to import "User icons" file in some way?

**Comment by jonathanlermitage** [comment]
If you asked to include `ExtraIconsSettings` while exporting IDE settings to a ZIP file, it will export every Extra Icons settings: UI scale, ignore list, the list of deactivated icons, and the list of User icons. 
You can use this file to import your settings in an IDE.

**Comment by amstiel** [comment]
Thanks again for the answers. 

I think we can close the issue now.

**Comment by jonathanlermitage** [comment]
You're welcome :-)
