### ISSUE TITLE
Upgrading ExtraIcons removes project specific user icons

### ISSUE THREAD

**Issue by techiemac** [jonathanlermitage/intellij-extra-icons-plugin#44]
I'm currently using goland and every time I upgrade extra icons, I notice the all of my project specific User Icons are blown away and the Override IDE settings was no longer checked.

This only appears to happen on upgrade

**Comment by jonathanlermitage** [comment]
Thx for this report. It may be related to https://github.com/jonathanlermitage/intellij-extra-icons-plugin/issues/41, but this time this is definitively a bug.  
I will look at this.  
Can you post your Goland IDE version (Help -> About -> the copy/past icon) ? Thx!

**Comment by jonathanlermitage** [comment]
Reproduced, and maybe fixed. It seems to be a bug with "[dynamic plugins](https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html?from=jetbrains.org)".  
Extra Icons should be upgradable without restart, and there is no major issue, except the bug you're facing :-D  
I tried to build a new release that forces IDE to restart to install plugin, and I did not loose the "Override IDE settings" setting.  
I will release Extra Icons 1.46.0 soon and open a ticket on JetBrains issue tracker.

**Comment by techiemac** [comment]
Sorry for the delay. Another datapoint, I am running on a mac. But here is the copypasta from my version info.
```
GoLand 2020.3.1
Build #GO-203.6682.164, built on December 28, 2020
Subscription is active until May 15, 2021.
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=true, ide.completion.variant.limit=500, debugger.watches.in.variables=false, suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: Key Promoter X, org.jetbrains.plugins.less, lermitage.intellij.extra.icons, net.seesharpsoft.intellij.plugins.csv, zielu.gittoolbox, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, uk.co.hadoopathome.intellij.avro.intellijavroviewer, com.intellij.plugins.html.instantEditing, com.intellij.swagger

```

**Comment by jonathanlermitage** [comment]
No problem :-)  
Thx, I will check on a similar configuration.

**Comment by jonathanlermitage** [comment]
Reproduced on a Mac, and it's fixed for me with 1.46 release. Does it work for you @techiemac?

**Comment by techiemac** [comment]
Sorry for the delay (again) in getting back to you. Yes! It works! Thanks for the quick fix.

**Comment by jonathanlermitage** [comment]
No problem :-)  
Thx for your feedback!  
Will publish a new release soon.

**Comment by matan129** [comment]
Does this mean that the plugin is now non-dynamic?
If so, are there any plans to bring it back to being dynamic?

**Comment by jonathanlermitage** [comment]
@matan129 yes, the plugin is not dynamic. It could be dynamic again, the [documentation](https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html#mark-extension-points-as-dynamic) says it should work, but JetBrains may have to fix some bugs first.  
Please look at [opened bugs](https://youtrack.jetbrains.com/issues/IDEA?q=%23dynamic-plugins%20&_ga=2.71320401.376261401.1620941271-1763171118.1572293543), especially [IDEA-262732](https://youtrack.jetbrains.com/issue/IDEA-262732). Unfortunately, some users are still affected by a bug that resets project-level plugin settings.
