### ISSUE TITLE
Storybook icon missing for mdx

### ISSUE THREAD

**Issue by sklawren** [jonathanlermitage/intellij-extra-icons-plugin#55]
Storybook allows you to write stories using mdx, but there isn't a match for ***.stories.mdx** files in the Storybook icon regex.

**Comment by jonathanlermitage** [comment]
Thx for this information @sklawren !  
I will add support for ***.stories.mdx** in the upcoming 1.52 release.

**Comment by jonathanlermitage** [comment]
Integrated into 1.52. Will publish a release soon.
