### ISSUE TITLE
Changing icons with folder

### ISSUE THREAD

**Issue by developerguchan** [jonathanlermitage/intellij-extra-icons-plugin#58]
I can't change icons with folder of svg files named html,css etc. how i can do this instead of changing icons one by one in settings?

**Comment by jonathanlermitage** [comment]
If my understanding is correct, you would like to change the icon of a folder containing specific files?  
Unfortunately, this is not supported, but it could be an improvement: 
- select a folder and an icon
- type a regex
- if the files in the folder match the regex, change the folder's icon
