### ISSUE TITLE
General Rule

### ISSUE THREAD

**Issue by developerguchan** [jonathanlermitage/intellij-extra-icons-plugin#59]
Hi, I want to create general rule, for example all directories should have this icon, if there is no specific icon. is it possible?

**Comment by jonathanlermitage** [comment]
I think this is not possible with this plugin. It knows when the plugin defines a custom icon for a folder, but it can't detect the fact that a folder is using the default icon provided by IntelliJ (the gray folder icon).  

You can probably create a Theme plugin for that:  
* clone or fork this repository: https://github.com/jonathanlermitage/intellij-extra-toolwindow-colorful-icons
* edit this file: https://github.com/jonathanlermitage/intellij-extra-toolwindow-colorful-icons/blob/main/src/main/java/lermitage/intellij/extratci/ExtraToolWindowIconsPatcher.java#L21 -> every item in the list defines two arguments: the first argument is the name of the icon in IntelliJ, the second argument is a customized icon. Delete all these items and add something like this: `icons.put("folder.svg", "/extratci/icons/your_custom_icon_for_default_folders.svg");` (I found "folder.svg here: https://jetbrains.design/intellij/resources/icons_list/ ; this is the list of all IntelliJ icons with their name")
* build and package the plugin: `./gradlew buildPlugin`: the plugin file is generated into `build/distributions/`. Install this plugin in your IDE, it should work ;)

**Comment by developerguchan** [comment]
Thank you but I don't know how to build it. after i change icons how can i build

**Comment by jonathanlermitage** [comment]
You should install a JDK (8 or 11; 16 may work too) and Gradle (any recent version), then run the command-line instruction: `./gradlew buildPlugin`.  
You can also open the project with IntelliJ: it bundles a Gradle distribution, and it can download a JDK for you.
