### ISSUE TITLE
Icon providers should be DumbAware

### ISSUE THREAD

**Issue by lppedd** [jonathanlermitage/intellij-extra-icons-plugin#6]
This will allow icons to be used even during the IDE initialization phase.

**Comment by jonathanlermitage** [comment]
Good idea!  
Done in https://github.com/jonathanlermitage/intellij-extra-icons-plugin/pull/5  
commit https://github.com/jonathanlermitage/intellij-extra-icons-plugin/pull/5/commits/0ae8b6c53dafc4387f7a38e2e365c7f38d141efa

**Comment by lppedd** [comment]
@jonathanlermitage Awesome! Thanks
