### ISSUE TITLE
add icon for dll extension

### ISSUE THREAD

**Issue by centralhardware** [jonathanlermitage/intellij-extra-icons-plugin#60]

**Comment by jonathanlermitage** [comment]
Sure. @centralhardware could you provide or suggest an PNG or SVG icon?  
Do you think we can reuse the "binary" icon? -> https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/ide203/src/main/resources/extra-icons/binary.svg

**Comment by centralhardware** [comment]
> Do you think we can reuse the "binary" icon?

I think this is acceptable

 I like this icon https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/ide203/src/main/resources/extra-icons/binary_alt.svg

**Comment by jonathanlermitage** [comment]
OK, I will include this in next release (1.58) :-)
