### ISSUE TITLE
Different Dockerfiles with prefix not supported

### ISSUE THREAD

**Issue by Florianisme** [jonathanlermitage/intellij-extra-icons-plugin#61]
It is common when dealing with multiple Dockerfiles to prefix the name of the files with their purpose, eg:

dev.Dockerfile
integration.Dockerfile

It would be nice if these Files would be recognized aswell and have the Docker Icon applied to them.

**Comment by jonathanlermitage** [comment]
Good idea!  
I will implement this in next release.
