### ISSUE TITLE
Ability to reuse bundled icon when creating user rule

### ISSUE THREAD

**Issue by bazzik** [jonathanlermitage/intellij-extra-icons-plugin#64]
**I would like to be able to reuse the existing/bundled icon instead of providing my own.**

An example:
- I have maybe like 20 bundled rules enabled only (disabled the rest: less regex checks on files).
- I want to have a rule for `robots.txt` file.
- I do not have any suitable icons for such file so I thought I will reuse existing one that I do not use (e.g. from Robot Framework rule). Sadly I cannot do that as I MUST provide my own icon.

### The reasoning:

Normally I would not bother with this kind of file: it's just 1 file in the website root, you are not editing it often (very rarely) and that's basically it.

But I have a particular project where 35+ domains share the same code base (very simple sites to show forms powered by Typeform and a few related actions; just 5-6 site-specific files). `robots.txt` is one of such "specific" files and they need to be different per site. So I though it makes sense to give them a separate icon in the Project View tree.

**This also can be used** if a user wants to add an additional pattern/rule to existing rule: you cannot edit bundled rule but can create a custom one and having the ability to use the same icon as bundled one will be great.

### The idea is:

Have a dropdown box with all bundled icons in addition to "specify your custom icon" element so the user can fill any of those 2 (and if both provided then give custom icon file a priority).

**Comment by jonathanlermitage** [comment]
Dev is almost done. Will be included in upcoming release.
