### ISSUE TITLE
Change rules for storybook

### ISSUE THREAD

**Issue by mongolyy** [jonathanlermitage/intellij-extra-icons-plugin#65]
Is it possible to change the rule for storybook file names to make the beginning optional?
I have a component called `LendingHistories.tsx` in my project, but I'm having trouble with it being recognized as a storybook under the current rules.

https://github.com/jonathanlermitage/intellij-extra-icons-plugin/pull/53#issuecomment-832041984
In order to meet @kubijo 's requirements, I think we just need to allow the filename `stor(y|ies).(js|ts)x` instead of making the beginning of the filename optional.

**Comment by jonathanlermitage** [comment]
Sure, we can associate `*.tsx` and `*.jsx` files to Storybook files. These extensions are already associated to React + Typescript, but users will simply deactivate the unwanted association :-)
