### ISSUE TITLE
Display custom file icons in Remote Host panel

### ISSUE THREAD

**Issue by bazzik** [jonathanlermitage/intellij-extra-icons-plugin#66]
This plugin shows custom file icons in Project View panel as well as Favorites.

What about Remote Host (when browsing the deployment target over FTP/SFTP/FTPS)? Can this be done there as well?

-----

Here are a few screenshots. Files in question: `.editorconfig` and `readme.md`

Local / Project View panel:
![image](https://user-images.githubusercontent.com/1482298/131113470-cdd79feb-b51f-456d-9711-5f1a476d56f7.png)

Favorites panel:
![image](https://user-images.githubusercontent.com/1482298/131113557-b66a3952-6952-47c0-80f2-a7996172c50e.png)

Remote Host:
![image](https://user-images.githubusercontent.com/1482298/131113805-17775084-09cb-486b-9b61-5888f04ab6b2.png)

**Comment by jonathanlermitage** [comment]
Yeah, good idea. JetBrains support helped me to show icons in the VCS view, but I don't know if we can do something for he Remote Host view. Actually, It's all about icons "providers": `FileIconProvider` handles Project and Favorites view, `FilePathIconProvider` handles VCS view, and I guess there is a provider for the Remote Hos view :-D  
I will investigate.

**Comment by Serial-ATA** [comment]
Hey @jonathanlermitage, have you looked into this? It looks like this might not be possible: https://github.com/mallowigi/a-file-icon-idea/issues/146#issuecomment-766297286.

**Comment by jonathanlermitage** [comment]
It's too complicated, and I lack of free time. I give up 😥
