### ISSUE TITLE
Incorrect Storybook extension regex

### ISSUE THREAD

**Issue by sklawren** [jonathanlermitage/intellij-extra-icons-plugin#69]
Your storybook icon regex is `*.tsx` and `*.jsx`. This causes all files use the Storybook icon including React components. These should be removed.

Only stories should use the Storybook icon. React components should still use the React icon.

You already have two other rules in the set for this which could actually become one rule.

`*.stories.mdx` and `*.stor(y|ies).(js|jsx|ts|tsx)`

You can make this into a single rule:

`*.stor(y|ies).(js|jsx|ts|tsx|mdx)`

**Comment by jonathanlermitage** [comment]
I associated tsx an jsx files to Rect and Storybook, according to https://github.com/jonathanlermitage/intellij-extra-icons-plugin/issues/65 
You can simply deactivate the tsx and jsx <-> Storybook associations, then these files will be associated to React.

**Comment by jonathanlermitage** [comment]
I could probably rework how priorities works in a future update, because React is probably more popular than Storybook.

**Comment by jonathanlermitage** [comment]
Otherwise, @mongolyy do you think we should associate Storybook files to `*.stor(y|ies).(js|jsx|ts|tsx|mdx)` only?  
If you are ok with that guys, I will revert https://github.com/jonathanlermitage/intellij-extra-icons-plugin/issues/65 and apply @sklawren 's suggetion.

**Comment by mongolyy** [comment]
@jonathanlermitage 
Thanks for the mention.

> do you think we should associate Storybook files to *.stor(y|ies).(js|jsx|ts|tsx|mdx) only?

Yes! I think we should associate Storybook files to `*.stor(y|ies).(js|jsx|ts|tsx|mdx)` only.
