### ISSUE TITLE
[Feature request] Custom icons

### ISSUE THREAD

**Issue by MatthiasKunnen** [jonathanlermitage/intellij-extra-icons-plugin#7]
Would it be possible to allow users to add icons of their own choosing?

**Comment by jonathanlermitage** [comment]
Yes, it is in the [todo / ideal for contribution list](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/CHANGELOG.md#todo-ideas-ideal-for-contribution) ;-)

**Comment by MatthiasKunnen** [comment]
ah, I didn't check the changelog :)

Perhaps you can make issues from the todos/ideas and add _help wanted_ label. That way people will find it faster using the conventional method. See https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels.

That being said I can potentially take a look at this. Since I've yet to develop an IntelliJ plugin and I currently find myself short of time it will probably not be in the near future though. Maybe in a week or two.

**Comment by jonathanlermitage** [comment]
Good idea! I'll create issues soon.
