### ISSUE TITLE
User-provided SVG not displaying in editor

### ISSUE THREAD

**Issue by lcdennison** [jonathanlermitage/intellij-extra-icons-plugin#84]
I'm experiencing a strange issue in PhpStorm 2021.3.1 (plugin version 1.69.3.203). My primary OS is Windows 10, but I use Ubuntu through Windows Subsystem for Linux (WSL). PhpStorm is installed in the WSL filesystem and graphical interface is provided to Windows through X11. Everything works fine, except these custom icons.

When I configure a user-provided icon in settings, everything appears to be correct. The icon preview (green square) is displayed, as shown below.

![image](https://user-images.githubusercontent.com/9526919/153698784-53903d63-8d9a-471f-a534-05b931493cd8.png)

As soon as I restart the IDE though, the associated file types (PHP traits, in this example) no longer show an icon at all, neither on the file list nor the editor tabs. Both shown below.

![image](https://user-images.githubusercontent.com/9526919/153698914-2851948d-4dba-42ac-875c-caa17d5be3e6.png)

![image](https://user-images.githubusercontent.com/9526919/153698926-ad4d48fd-c41a-4908-87d0-f6d8a3b2d916.png)

However, if I go back into Extra Icons settings, the custom icon I set is still there, including the preview of it. It's just not showing in the editor itself.

I tried this same exact process (using the same file) on my Windows instance of PhpStorm. It's the same version, just installed on Windows instead of Ubuntu/WSL. The icon shows up just fine there, so the issue seems to be related to the Linux version, WSL, or my X11 setup.

This only happens with user-provided files. Custom icons bundled with the plugin work as expected. You can see my debug below, but I'm at a loss for how to diagnose further. Any ideas?

## Attempted solutions/debug

Suspecting a WSL/Windows filesystem issue, I tried selecting the icon file from WSL filesystem and also my Windows filesystem. Neither one worked. The plugin loads the icon preview (in the settings menu) either way.

I then looked into the plugin code and found the try/catch where IO exceptions would be handled: https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/593743201f0f013e3efce4a9dfe5504c34bd65d6/src/main/java/lermitage/intellij/extra/icons/ExtraIconPatcher.java#L68-L77 

But when I looked in the logs, I only found: `[...] INFO - j.extra.icons.ExtraIconPatcher - config loaded with success, enabled 2 items`  (I had two icons defined at the time). The warning in the catch block does not appear in my log. And I confirmed that an SVG file was indeed being written to the `/tmp` directory:

![image](https://user-images.githubusercontent.com/9526919/153699353-c7de495c-ad5b-413c-b256-5cde69c39956.png)

Suspecting permissions issue, I tried launching PhpStorm as root, but that had the same error.

Detailed version info:
```
PhpStorm 2021.3.1
Build #PS-213.6461.83, built on December 29, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.60.1-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.27.0)
    Statistic (4.1.7)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2021.07.18.002)
    com.deadlock.scsyntax (213.5744.190)
    pro.bashsupport (2.1.2.213)
    aws.toolkit (1.37-213)
    lermitage.intellij.extra.icons (1.69.3.203)

Current Desktop: Undefined
```

**Comment by jonathanlermitage** [comment]
Thx for this report!  
This issue may be caused by https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/ide203/src/main/java/lermitage/intellij/extra/icons/ExtraIconPatcher.java#L97  
The IDE icon patcher ([IconPathPatcher) ](https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/util/IconPathPatcher.java)works with icons from the classpath. It also works with local files using the `file://` syntax, but I believe WSL `\\wsl$` paths are not well supported by the icon patcher. I will investigate and submit an issue to JetBrains if needed.

**Comment by lcdennison** [comment]
@jonathanlermitage Sure. Here's the new message:
```
2022-02-12 21:31:10,551 [   2184]   WARN - j.extra.icons.ExtraIconPatcher - local file: file:///tmp/extra-icons-ide-user-icon1428773998666350403.svg
2022-02-12 21:31:10,551 [   2184]   INFO - j.extra.icons.ExtraIconPatcher - config loaded with success, enabled 7 items
```

So it looks like the path is correct. That file exists in the WSL filesystem at `/tmp/extra-icons-ide-user-icon1428773998666350403.svg`

Could it be permissions? The file is written with 600 permissions. I tried using PhpStorm launched as root, and that didn't work either. As far as I can see, PhpStorm IS running as root, but maybe it's downgrading itself somewhere such that it still doesn't have permission to that file? I'd assume that'd throw an IO exception, though.

Sorry for the hassle. I'd add debugging/logging code myself to further evaluate, but I'm not familiar with the JetBrains plugins architecture or Kotlin/Java setup enough for that to be a trivial thing.

**Comment by lcdennison** [comment]
@jonathanlermitage This issue seems to be resolved now. I'm not sure exactly when it happened as I just recently updated the plugin. I also coincidentally upgraded to 2022.1. Regardless, it's solved for me. Thanks for the work!

**Comment by jonathanlermitage** [comment]
Thx for your feedback! 👍
