### ISSUE TITLE
.prettierrc.yml not correctly identified

### ISSUE THREAD

**Issue by mofada** [jonathanlermitage/intellij-extra-icons-plugin#88]
![image](https://user-images.githubusercontent.com/22286246/157997588-9a3f6b26-ddad-4d62-a70a-20f92153e111.png)

**Comment by jonathanlermitage** [comment]
Fox now, only `.prettierrc` is supported. I will add support for `.prettierrc.yml` too.

**Comment by mofada** [comment]
https://prettier.io/docs/en/configuration.html

![image](https://user-images.githubusercontent.com/22286246/158001269-72ac0d3b-5226-4579-85f5-b1ce33a376d4.png)

**Comment by jonathanlermitage** [comment]
Fixed. It will be part of the 2022.1.2 release.
