### ISSUE TITLE
Offering a one time payment

### ISSUE THREAD

**Issue by HuiiBuh** [jonathanlermitage/intellij-extra-icons-plugin#89]
Hi as a developer how maintains an open source chrome extension for quite a lot of people, I totally understand and support your decision to make this plugin a played plugin. 
But I *really* hate subscriptions. Is there any way that you could offer the options to send you a one time payment (obviously more than 5$) in order to get access to the extension.

**Comment by jonathanlermitage** [comment]
Hi @HuiiBuh!  
I rely on the subscription model offered by JetBrains. Unfortunately, there is no option to buy lifetime licenses. A solution would be to implement my own license server, but I'm not ready to do that: I don't want to handle payments by myself, it's too risky and I have a limited experience on security.  
However, I activated the option to offer fallback licenses. That means you can pay for a 1-year subscription, then, if you're happy with the release you get a the end of the year, you don't have to renew your subscription and can use this release forever.

**Comment by HuiiBuh** [comment]
Hi, I was not aware of the options Jetbrains offers. But this sounds good to...
So thanks for maintaining the plugin and feel free to close the issue if you want to

**Comment by jonathanlermitage** [comment]
No problem! Thx! 😃
