### ISSUE TITLE
Add an option to customize file detection patterns

### ISSUE THREAD

**Issue by jonathanlermitage** [jonathanlermitage/intellij-extra-icons-plugin#9]
Rework icon providers and setting panel to let user modify or add new file patterns.

**Comment by jonathanlermitage** [comment]
Good idea. Registered `dockerfile*` pattern (commit 352f5a0771f74e3dadfd310dfc1fea8e7721671d).

**Comment by acgetchell** [comment]
Would also fix AppVeyor not being detected because I'm using .appveyor.yml (which is supported) instead of appVeyor.yml.

**Comment by jonathanlermitage** [comment]
Fixed in a9ff411c93a21c938770770024c52ac3943b7823. Will publish 1.13.0 release soon :-)

**Comment by jonathanlermitage** [comment]
new settings panel provides a way to register custom icons. Closing this issue.

**Comment by cinan** [comment]
> new settings panel provides a way to register custom icons. Closing this issue.

I simply want change typescript .ts to .tsx. I don't see how I could do that in User icons.

**Comment by jonathanlermitage** [comment]
@cinan you can go to User Icons tab, then register a new File Pattern with "*.tsx" regex, and pick icon from https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/resources/icons/typescript.svg

**Comment by cinan** [comment]
@jonathanlermitage thanks for quick fix, but this is extremely unintuitive. What I'd imagine as an correct solution is to double click on a row in Plugin icons list and edit regexp/pattern/wildcard (similar to Preferences/Editor/File Types settings).

**Comment by jonathanlermitage** [comment]
I think User Icons are a good workaround, but I totally agree with you, it would be cool to edit the Plugins icons list. I'll open a new issue. Of course, contributions are welcome :-D
