### ISSUE TITLE
The regular expression rule for finished .js and .ts configuration files is overridden by the *.js and *.ts rule

### ISSUE THREAD

**Issue by francmarin98** [jonathanlermitage/intellij-extra-icons-plugin#93]
For some strange reason it seems to bug min with config files ending in .js and .ts.

What I mean is that for some strange reason the regular expression in the configuration files is "ignored". An example is the postcss and tailwind files that I added in the previous version, the added regular expression detects the file but the plugin as it gives more relevance to the *.js rule and does not link the icon correctly.

![image](https://user-images.githubusercontent.com/50973629/163517141-f5c7aaa5-ed33-470f-8e8a-65c171ab2aac.png)

**Comment by jonathanlermitage** [comment]
Yeah, it's weird. The PostCss  model is defined before TestJavascript, so you should see the PostCss icon. Same thing for Tailwind. 
At least, I reproduced this bug. I will investigate.

**Comment by jonathanlermitage** [comment]
Ho, ok, there is a problem with the regex. `postcss.config.js` matches, but we apply the regex on the file's full path, something like `foo/bar/postcss.config.js`.

**Comment by jonathanlermitage** [comment]
In `^(\.postcssrc|postcss\.config)(\.[cm]?js|ts|json|ya?ml)?$` we can replace `^` with `.*`. I will fix this asap, and add some documentation.

**Comment by jonathanlermitage** [comment]
I uploaded a fix: [Extra Icons-2022.1.2.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8493927/Extra.Icons-2022.1.2.zip). It's ok on my machine. Can you make a try?
Thx!

**Comment by francmarin98** [comment]
I have done the tests and now it works correctly. I'll take into account structuring the regular expression for the next collaboration.

![image](https://user-images.githubusercontent.com/50973629/163578851-d4c18099-b936-4162-8b32-aba717a65d4f.png)

By the way, not that I want to spam but I also want to share that I have created a theme for the IDEs, it is called Moonlight Theme.
