### ISSUE TITLE
Enabling Extra Icons freezes the IDE.

### ISSUE THREAD

**Issue by jmatias** [jonathanlermitage/intellij-extra-icons-plugin#99]
## Issues

The IDEA becomes completely unresponsive.

![image](https://user-images.githubusercontent.com/1302269/173488507-0d761e5e-d3f9-42d8-a5ac-486a26f61bae.png)

[report.txt](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896113/report.txt)

[threadDump-20220613-225215.txt](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896137/threadDump-20220613-225215.txt)
[threadDump-20220613-225220.txt](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896138/threadDump-20220613-225220.txt)
[threadDump-20220613-225225.txt](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896139/threadDump-20220613-225225.txt)
[threadDump-20220613-225230.txt](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896140/threadDump-20220613-225230.txt)
[threadDump-20220613-225236.txt](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896141/threadDump-20220613-225236.txt)

I've included a few of the thread dumps, but they all seem to be the same. 

![image](https://user-images.githubusercontent.com/1302269/173488055-19ce1d63-c7c5-412b-80dc-a17018beace4.png)

![image](https://user-images.githubusercontent.com/1302269/173488177-8ce865b2-12d5-41d4-9d3c-20437762978d.png)

```
IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
Build #IU-222.2964.55, built on June 9, 2022
Licensed to IntelliJ IDEA EAP user: Javier Matias
Expiration date: July 9, 2022
Runtime version: 17.0.3+7-b469.3 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 8000M
Cores: 10
Metal Rendering is ON
Registry:
    ide.mac.transparentTitleBarAppearance=false
    ide.balloon.shadow.size=0
    scala.erase.compiler.process.jdk.once=false
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    some.awesome (1.14)
    org.jetbrains.plugins.rest (222.2964.16)
    name.kropp.intellij.makefile (222.2964.55)
    me.lensvol.blackconnect (0.5.0)
    hu.hawser.co-author-plugin (2.3)
    de.netnexus.camelcaseplugin (3.0.12)
    com.jetbrains.plugins.ini4idea (222.2964.63)
    com.intellij.plugins.macoskeymap (222.2964.16)
    com.intellij.nativeDebug (222.2964.16)
    com.intellij.properties.bundle.editor (222.2964.16)
    com.intellij.datagen (222.2964.16)
    Shifter (1.9.6)
    Keymap exporter (2.2)
    zielu.gittoolbox (212.9.0)
    mobi.hsz.idea.gitignore (4.4.1)
    FrameSwitcher (3.31.0-212)
    com.intellij.tide (222.2964.16)
    Pythonid (222.2964.55)
    R4Intellij (222.2964.55)
    ru.adelf.idea.dotenv (2022.2)
    com.chrisrm.idea.MaterialThemeUI (7.6.2)
    org.intellij.scala (2022.2.4)
    com.intellij.bigdatatools (222.1015.3)
    izhangzhihao.rainbow.brackets (6.24)
    pro.bashsupport (2.1.8.222)
    lermitage.intellij.extra.icons (2022.1.4)

Kotlin: 222-1.7.0-RC-246-IJ2964.55

```

**Comment by jmatias** [comment]
Update: Disabling all Angular icons seems to be resolve the issue.

![image](https://user-images.githubusercontent.com/1302269/173489492-f133f79c-ef20-4be1-8f10-96ae491e5ee3.png)

**Comment by jonathanlermitage** [comment]
Thx for your report!  
The Angular support looks for angular.json files in the project, but it seems to spend too much time. Some well-known big folders are excluded, like `node_modules/`, `out/` etc, but it could be improved.  
I will publish a patch asap in order to add a time limiter (something like 500ms, it should be fast, otherwise this is not normal), and I will investigate on this issue.

**Comment by jonathanlermitage** [comment]
@jmatias Also, could you please send the IDE log file? (Help > Show Logs in Explorer > `idea.log`)  
You should see a line like `Will scan these folders for angular.json files: [ a list of folder paths ]`. This list would be interesting. It should contain the project's path, and any "attached" folder.  
Thx!

**Comment by jonathanlermitage** [comment]
Added a time limiter (500ms). If we reach this limit, we cancel the search and we simply look for an `angular.json` file at project's base path only.  
Can you please try this build? 
[Extra Icons-2022.1.4.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896553/Extra.Icons-2022.1.4.zip)
Thx!

**Comment by jmatias** [comment]
I did a quick search for those strings and couldn't find anything. I can give your build a try though.

![image](https://user-images.githubusercontent.com/1302269/173711627-f2a89cb4-fad9-4759-806a-c515e094fdfb.png)

**Comment by jmatias** [comment]
> Added a time limiter (500ms). If we reach this limit, we cancel the search and we simply look for an `angular.json` file at project's base path only. Can you please try this build? [Extra Icons-2022.1.4.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8896553/Extra.Icons-2022.1.4.zip) Thx!

New seems to work fine

**Comment by jonathanlermitage** [comment]
Thx! I will publish this release asap.  
For the logs, you should see an `idea.log` file. Otherwise, you can go to `Help` > `Collect Logs and Diagnostic Data`. It will produce a zip file with the log files: `idea.log` (and previous logs like `idea.1.log`, `idea.2.log`, etc) files, `troubleshooting.txt`, etc.

**Comment by jonathanlermitage** [comment]
Wooohoohoo 🥳, please don't waste time with the log files. Finally, I found a way to find `angular.json` files with the IntelliJ SDK, it's super fast and it should be totally safe (it uses the project's files index generated by the IDE).  
I just submitted the 2022.1.5 release with the fix, and I will integrate improvements in the 2022.1.6 release.

**Comment by jmatias** [comment]
Happy to help
